repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      -   id: trailing-whitespace
      -   id: end-of-file-fixer
      -   id: check-yaml
      -   id: check-added-large-files

  - repo: local
    hooks:
      - id: tox
        name: tox
        entry: tox
        language: system
        types: [python]

  - repo: local
    hooks:
      - id: render_questions
        name: render_questions
        entry: python src/render_questions.py
        language: system
        types: [python]
